CREATE TABLE `tbl_user` (
  `itemID` BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '记录ID',
  
  `userName` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '用户名称',
  `phone` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '用户手机号',

  `action` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '记录状态',
  `actionTime` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '记录修改时间',
  `createTime` BIGINT(20) NOT NULL DEFAULT '0' COMMENT '记录创建时间'
  
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';